/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PostTest2;

import java.awt.Color;

/**
 *
 * @author ARIF
 */
public class Posttest2 extends javax.swing.JFrame {

    /**
     * Creates new form Posttest4
     */
    public Posttest2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        wni = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        kec = new javax.swing.JTextField();
        wna = new javax.swing.JRadioButton();
        kerja = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tgl = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        bln = new javax.swing.JComboBox();
        cetak = new javax.swing.JButton();
        cetak1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tempat = new javax.swing.JTextField();
        lk = new javax.swing.JRadioButton();
        alamat = new javax.swing.JTextField();
        pr = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rw = new javax.swing.JTextField();
        rt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        agama = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        kwn = new javax.swing.JRadioButton();
        kwn1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        desa = new javax.swing.JTextField();
        thn = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        gd = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup3.add(wni);
        wni.setText("WNI");
        wni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wniActionPerformed(evt);
            }
        });
        jPanel1.add(wni, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 377, -1, -1));

        jLabel12.setText("Status Perkawinan");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 321, 105, 22));
        jPanel1.add(kec, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 266, 300, -1));

        buttonGroup3.add(wna);
        wna.setText("WNA");
        wna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wnaActionPerformed(evt);
            }
        });
        jPanel1.add(wna, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 374, -1, -1));
        jPanel1.add(kerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 350, 300, -1));

        jLabel13.setText("Pekerjaan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 349, 105, 22));

        tgl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 116, 60, -1));

        jLabel14.setText("Kewarganegaraan");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 377, 105, 22));

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 105, 22));

        nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikActionPerformed(evt);
            }
        });
        jPanel1.add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 54, 300, -1));

        bln.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(bln, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 116, 55, -1));

        cetak.setText("CETAK");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        jPanel1.add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 418, 93, 37));

        cetak1.setText("HAPUS");
        cetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetak1ActionPerformed(evt);
            }
        });
        jPanel1.add(cetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 418, 93, 37));

        jLabel4.setText("Tempat/Tgl Lahir");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 105, 22));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 85, 300, -1));

        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, 105, 22));

        tempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatActionPerformed(evt);
            }
        });
        jPanel1.add(tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 116, 92, -1));

        buttonGroup1.add(lk);
        lk.setText("LAKI-LAKI");
        jPanel1.add(lk, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 148, -1, -1));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 182, 300, -1));

        buttonGroup1.add(pr);
        pr.setText("PEREMPUAN");
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });
        jPanel1.add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 148, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM KTP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 11, 164, 25));

        jLabel7.setText("Alamat");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 105, 22));
        jPanel1.add(rw, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 50, -1));
        jPanel1.add(rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 210, 50, -1));

        jLabel8.setText("RW");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 69, 22));

        jLabel15.setText("RT");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 209, 69, 22));

        agama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISLAM", "PROTESTAN", "KATOLIK", "HINDU", "BUNDHA" }));
        jPanel1.add(agama, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 294, 100, -1));

        jLabel9.setText("Kel/Desa");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 237, 69, 22));

        buttonGroup2.add(kwn);
        kwn.setText("KAWIN");
        kwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kwnActionPerformed(evt);
            }
        });
        jPanel1.add(kwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 321, 100, -1));

        buttonGroup2.add(kwn1);
        kwn1.setText("BELUM KAWIN");
        kwn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kwn1ActionPerformed(evt);
            }
        });
        jPanel1.add(kwn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 319, 131, -1));

        jLabel10.setText("Kecamatan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 265, 69, 22));

        jLabel11.setText("Agama");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 293, 105, 22));

        jLabel2.setText("NIK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, 26));
        jPanel1.add(desa, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 238, 300, -1));

        thn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999" }));
        jPanel1.add(thn, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 116, 73, -1));

        jLabel6.setText("Gol. Darah");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 148, 60, 22));

        gd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "A", "B", "O" }));
        jPanel1.add(gd, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 149, 48, -1));

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wniActionPerformed

    private void wnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wnaActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here
        String vnik = nik.getText();
        String vnama = nama.getText();
        String vtempat = tempat.getText();
        String valamat = alamat.getText();
        String vrt =rt.getText();
        String vrw =rw.getText();
        String vdesa = desa.getText();
        String vkec = kec.getText();
        String vkerja = kerja.getText();
        
        String JenisKelamin=null;
        if (lk.isSelected()) {
            JenisKelamin = lk.getText();
        }else if (pr.isSelected()) {
            JenisKelamin = pr.getText();
        }
        
        String Status=null;
        if (kwn.isSelected()) {
            Status = kwn.getText();
        }else if (kwn1.isSelected()) {
            Status = kwn1.getText();
        }
        
        String warga=null;
        if (wni.isSelected()) {
            warga = wni.getText();
        }else if (wna.isSelected()) {
            warga = wna.getText();
        }
        
        String vtgl = tgl.getSelectedItem().toString();
        String vbln = bln.getSelectedItem().toString();
        String vthn = thn.getSelectedItem().toString();
        String vgd = gd.getSelectedItem().toString();
        String vagama = agama.getSelectedItem().toString();
        
        hasil.setBackground(Color.BLUE);
        hasil.setText("\t              KARTU TANDA PENDUDUK"+"\n\n   NIK\t         : "+vnik+"\n\n   Nama\t         : "+vnama+"\n   Tempat/Tgl Lahir    : "+vtempat+", "+vtgl+"-"+vbln+"-"+vthn+
        "\n   Jenis Kelamin         : "+JenisKelamin+"     Gol Darah : "+vgd+"\n   Alamat\t         : "+valamat+"\n             RT/RW            : "+vrt+"/"+vrw+
        "\n             Kel/Desa        : "+vdesa+"\n             Kecamatan    : "+vkec+
        "\n   Agama\t         : "+vagama+"\n   Status\t         : "+Status+"\n   Pekerjaan\t         : "+vkerja+"\n   Kewarganegaraan : "+warga+"\n");
    }//GEN-LAST:event_cetakActionPerformed

    private void tempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prActionPerformed

    private void kwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kwnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kwnActionPerformed

    private void kwn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kwn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kwn1ActionPerformed

    private void cetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetak1ActionPerformed
        // TODO add your handling code here:
        hasil.setBackground(Color.WHITE);
        hasil.setText(null);
        nik.setText("");
        nama.setText("");
        tempat.setText("");
        alamat.setText("");
        rt.setText("");
        rw.setText("");
        desa.setText("");
        kec.setText("");
        kerja.setText("");
        tgl.setSelectedItem("1");
        bln.setSelectedItem("01");
        thn.setSelectedItem("1990");
        gd.setSelectedItem("-");
        agama.setSelectedItem("ISLAM");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
    }//GEN-LAST:event_cetak1ActionPerformed

    private void nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Posttest2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox agama;
    private javax.swing.JTextField alamat;
    private javax.swing.JComboBox bln;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cetak;
    private javax.swing.JButton cetak1;
    private javax.swing.JTextField desa;
    private javax.swing.JComboBox gd;
    private javax.swing.JTextArea hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kec;
    private javax.swing.JTextField kerja;
    private javax.swing.JRadioButton kwn;
    private javax.swing.JRadioButton kwn1;
    private javax.swing.JRadioButton lk;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JRadioButton pr;
    private javax.swing.JTextField rt;
    private javax.swing.JTextField rw;
    private javax.swing.JTextField tempat;
    private javax.swing.JComboBox tgl;
    private javax.swing.JComboBox thn;
    private javax.swing.JRadioButton wna;
    private javax.swing.JRadioButton wni;
    // End of variables declaration//GEN-END:variables
}
